---
- hosts: all
  tasks:
    - ansible.builtin.debug:
        var: ansible_facts['devices']['vdc']
    
    - set_fact:
        device: vdc
      when: not 'vdb' in ansible_facts['devices']

    - debug:
        var: device  
