---
- hosts: localhost
  tasks:
    - name: Split variable loop
      set_fact:
        servers: "{{ hosts_list | split('\n') }}"
   
    - name: Debug hostname
      ansible.builtin.debug:
        msg: "snap_{{ item }}_{{ lookup('pipe', 'date +%Y-%m-%d') }}"
      loop: "{{ servers }}"