---
- hosts: sat01
  tasks:   
    - name: find all CVs
      redhat.satellite.resource_info:
        organization: "JF_LOCAL"
        resource: content_views
        server_url: http://sat01.jferre.local
        username: jferre
        password: "redhat@123"
      register: all_cvs

    - set_fact:
        cv_name: "{{ (cv_name|default([])) + [item.name] }}"
      with_items: "{{ all_cvs.resources }}"

    - name: Include role satellite
      ansible.builtin.include_role:
        name: satellite
        tasks_from: content_view.yml
      loop: "{{ cv_name }}" 
