---
- hosts: bastion 
  gather_facts: false
  vars:
    hostname: 192.168.15.251
    username: administrator@jferre.local
    password: Redhat@123
    datacenter: dc01.jferre.local
  tasks:
    - name: Get RHEL 9 version
      ansible.builtin.set_fact:
        template: "template_rhel9"
      when: so_version == "RHEL 9"

    - name: Get RHEL 8 version
      ansible.builtin.set_fact:
        template: "template_rhel8"
      when: so_version == "RHEL 8"

    - name:  Clone a virtual machine from Linux template and customize
      community.vmware.vmware_guest:
        hostname: "{{ hostname }}" 
        username: "{{ username }}"
        password: "{{ password }}"
        datacenter: "{{ datacenter }}"
        state: present
        folder: "VMs"
        template: "{{ template }}"
        name: "{{ vm_name }}"
        wait_for_ip_address: true
        validate_certs: false
        networks:
          - ip: "{{ ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
      register: create_vm

     - name: Get IP Address
       set_fact:
         ip_address: "{{ instance.hw_eth0.ipaddresses[0] }}"

#    - name: Provision a VM
#      ansible.builtin.import_role:
#        name: cloud.vmware_ops.provision_vm
#      vars:
#        provision_vm_hostname: "{{ hostname }}"
#        provision_vm_username: "{{ username }}"
#        provision_vm_password: "{{ password }}"
#        provision_vm_validate_certs: false
#        provision_vm_folder: "VMs"
#        provision_vm_datacenter: "{{ datacenter }}"
#        provision_vm_name: "{{ vm_name }}"
#        provision_vm_template: "{{ template }}"
#        provision_vm_state: "poweredon"
#        provision_vm_wait_for_ip_address: true
#      register: create_vm
