---
- hosts: localhost 
  gather_facts: false

  vars_files: 
    - group_vars/vmware.yml

  tasks:
    - name:  Clone a virtual machine from Linux template and customize
      community.vmware.vmware_guest:
        hostname: "{{ vcenter['hostname'] }}" 
        username: "{{ vcenter['username'] }}"
        password: "{{ vcenter['password'] }}"
        datacenter: "{{ vcenter['datacenter'] }}"
        state: present
        folder: "VMs"
        template: "template-rhel9"
        name: "rhel9-aap"
        wait_for_ip_address: true
        validate_certs: false
      register: create_vm

    - name: Get IP Address
      set_fact:
        dhcp_vm_ip: "{{ create_vm.instance.hw_eth0.ipaddresses[0] }}"

    - name: Execute changes on server
      delegate_to: "{{ dhcp_vm_ip }}"
      block:
        - name: Set hostname
          become: true
          become_user: root
          ansible.builtin.hostname:
            name: "rhel9-aap"

        - name: Set IP on server
          community.general.nmcli:
            type: ethernet
            conn_name: ens33
            ip4: '192.168.15.223/24'
            gw4: '192.168.15.1'
            state: present

        - name: Reboot machine
          ansible.builtin.shell: "sleep 5 && reboot"
          async: 1
          poll: 0

    - name: Wait for backup machine with new IP
      wait_for:
        host: 192.168.15.223
        port: 22
