---
- hosts: localhost 
  gather_facts: false

  vars_files:
    - roles/satellite/vars/main.yml

  tasks:
    - name: Get satellite organizations and create it
      include_role:
        name: satellite
        tasks_from: manage_organizations.yml
