---
- hosts: localhost 
  gather_facts: false

  vars_files:
    - roles/satellite/vars/main.yml

  tasks:
    - name: Get organizations and create them at new Satellite
      include_role: 
        name: satellite
        tasks_from: manage_organizations

    - name: Create resources usign ID from all organizations
      include_role:
        name: satellite
        tasks_from: managing_all_resources
      with_items: "{{ org_id }}"
