---
- hosts: localhost 
  gather_facts: false

  vars_files:
    - roles/satellite/vars/main.yml

  tasks:
    - name: Get organizations and create them on new Satellite
      include_role: 
        name: satellite
        tasks_from: manage_organizations.yml

    - name: Get content views from organizations and create 
      include_role: 
        name: satellite
        tasks_from: manage_content_views.yml
      with_items: "{{ org_name }}"

    - name: Get activation keys from organizations and create
      include_role: 
        name: satellite
        tasks_from: manage_activation_keys.yml
      with_items: "{{ org_id }}"
