---
- hosts: bastion 
  gather_facts: false
  tasks:
    - name: "Reserve an IP address"
      codeaffen.phpipam.address:
        username: "admin"
        password: "redhat123"
        server_url: "http://ipam.jferre.local"
        address: "192.168.122.43"
        section: "Customers"
        description: "IP Reserved to RHEL9-APP"
        subnet: "192.168.122.0/24"
        is_gateway: no
        state: present
        validate_certs: false
