---
- name: Collect content views from old Satellite in {{ org_name_from_resource }}
  ansible.builtin.uri:
    url: "https://{{ satellite['old'] }}/katello/api/organizations/{{ resource_from_org_id }}/content_views"
    user: "{{ satellite['username'] }}"
    password: "{{ satellite['password'] }}"
    force_basic_auth: true
    validate_certs: false
  register: info_cvs

- name: Fix variable with content_views names
  ansible.builtin.set_fact: 
    content_views_id: "{{ info_cvs.json.results | map(attribute='id') }}"

- name: Including task to create content views in loop 
  include_tasks: create_content_views.yml
  with_items: 
    - "{{ content_views_id }}"
  loop_control:
    loop_var: get_attributes_from_cvs
