---
- name: Get organizations name from {{ satellite['old'] }}
  redhat.satellite.organization_info:
    username: "{{ satellite['username'] }}"
    password: "{{ satellite['password'] }}"
    server_url: "https://{{ satellite['old'] }}"
    validate_certs: false
  register: info_org

- ansible.builtin.set_fact: 
    org_id: "{{ info_org.organizations | map(attribute='id') }}"
    org_name: "{{ info_org.organizations | map(attribute='name') }}"

- name: Create organizations in {{ satellite['new'] }}
  redhat.satellite.organization:
    username: "{{ satellite['username'] }}"
    password: "{{ satellite['password'] }}"
    server_url: "https://{{ satellite['new'] }}"
    validate_certs: false
    name: "{{ item }}"
  with_items:
    - "{{ org_name }}"
  when: create_resource is defined
