---
- name: Collect name from organization
  include_tasks: get_org_name_to_resource.yml

- name: Get activation keys from old Satellite
  ansible.builtin.uri:
    url: "https://{{ satellite['old'] }}/katello/api/organizations/{{ resource_from_org_id }}/activation_keys"
    user: "{{ satellite['username'] }}"
    password: "{{ satellite['password'] }}"
    force_basic_auth: true
    validate_certs: false
  register: info_aks

- name: Fix variable with activation keys ID
  ansible.builtin.set_fact:
    id_activation_keys: "{{ info_aks.json.results | map(attribute='id') }}"

- name: Including task to create activation keys in loop
  include_tasks: create_activation_keys.yml
  with_items: 
    - "{{ id_activation_keys }}"
  loop_control:
    loop_var: get_name_hc_from_ak
