---
- name: Including tasks to creating host collections
  include_tasks: manage_host_collections.yml

- name: Including tasks to creating activation keys
  include_tasks: manage_activation_keys.yml

- name: Including tasks to locations
  include_tasks: manage_locations.yml
