---
- hosts: bastion
  tasks:
    - name: Create DNS record
      vars:
        ansible_connection: winrm
        ansible_user: administrator 
        ansible_password: redhat@123
        ansible_port: 5985
        ansible_winrm_transport: ntlm
      delegate_to: ad01
      community.windows.win_dns_record:
        name: "{{ servername }}"
        type: "A"
        value: "{{ ipaddress }}"
        zone: "{{ domain }}"
