---
- name: Playbook de teste para o pessoal
  hosts: ad01 
  vars:
    ansible_connection: winrm
    ansible_user: administrator 
    ansible_password: redhat@123
    ansible_port: 5985
    ansible_winrm_transport: ntlm
    usuario_espelho: Joao Ferreira
  tasks:
    - name: Consulta usuario espelho no AD
      microsoft.ad.object_info:
        ldap_filter: (&(Name={{ usuario_espelho }}))
        properties:
          - DistinguishedName
          - MemberOf
        search_base: DC=jferre,DC=local
      register: aduser_properties

    - name: Obter OU e grupos do usuário
      set_fact:
        aduser: "{{ (aduser_properties.objects | map(attribute='DistinguishedName'))[0] }}"
        aduser_gp: "{{ aduser_properties.objects | map(attribute='MemberOf') }}"

    - name: Organiza OU do usuário
      set_fact:
        aduser_cn: "{{ (aduser | split(','))[1:] }}"

    - name: Transforma a lista das informações em uma linha
      set_fact:
        aduser_ou: "{{ aduser_cn | join(',') }}"

    - name: Cria um novo usuário no AD com base no usuário espelho
      microsoft.ad.user:
        identity: Roger Principe
        password: redhat@123
        state: present
        path: "{{ aduser_ou }}"
        groups:
          set: "{{ aduser_gp }}"
