---
- hosts: bastion
  tasks:
    - name: Consult AD user
      vars:
        ansible_connection: winrm
        ansible_user: administrator 
        ansible_password: redhat@123
        ansible_port: 5985
        ansible_winrm_transport: ntlm
      delegate_to: ad01
      microsoft.ad.object_info:
        filter: Name -like '{{ mirror_user }}'
        properties:
          - objectSid
          - MemberOf
        search_base: DC=jferre,DC=local
      register: aduser_properties

    - name: Get CN from all users
      set_fact:
        aduser: "{{ (aduser_properties.objects | map(attribute='DistinguishedName'))[0] }}"
        aduser_gp: "{{ (aduser_properties.objects | map(attribute='MemberOf'))[0] }}"
    
    - name: Save all groups in file
      ansible.builtin.lineinfile:
        line: "{{ (item | split(','))[0] }}"
        path: /tmp/groups
        create: yes
      with_items: "{{ aduser_gp }}"

    - name: Get groups to set in new user
      ansible.builtin.slurp:
        src: /tmp/groups
      register: adgroups

    - name: Remove file
      ansible.builtin.file:
        path: /tmp/groups
        state: absent

    - set_fact:
        aduser_group_cn: "{{ adgroups['content'] | b64decode }}"
        aduser_cn: "{{ (aduser | split(','))[1:] }}"

    - set_fact:
        aduser_ou: "{{ aduser_cn | join(',') }}"
        adgroups_list: "{{ aduser_group_cn.split('\n') | regex_replace('CN=') }}"

    - name: Create an user in AD
      vars:
        ansible_connection: winrm
        ansible_user: administrator 
        ansible_password: redhat@123
        ansible_port: 5985
        ansible_winrm_transport: ntlm
      delegate_to: ad01    
      microsoft.ad.user:
        identity: Roger Principe
        password: redhat@123
        state: present
        path: "{{ aduser_ou }}"
        groups:
          set: "{{ adgroups_list }}"
