---
hardware:
  - regexp: hostname
    variable: "{{ansible_facts['hostname']}}"
  - regexp: biosversion
    variable: "{{ansible_facts['bios_version']}}"
  - regexp: ipaddress
    variable: "{{ansible_facts['default_ipv4']['address']}}"
  - regexp: fqdn
    variable: "{{ansible_facts['fqdn']}}"
  - regexp: cpu
    variable: "{{ansible_facts['processor_count']}}"
  - regexp: memtotal_mb
    variable: "{{ansible_facts['memtotal_mb']}} MB"
