---
- hosts: bastion
  gather_facts: false
  tasks:
    - add_host:
        name: "{{ vmname }}"
        group: created

- hosts: created
  gather_facts: false
  tasks:
    - shell: hostname
      register: hostname

    - debug:
        var: hostname.stdout
